### ISSUE TITLE
SetDesiredCapacityInfo lowered the number of nodes in ASG

### ISSUE THREAD

**Issue by russki** [TwiN/aws-eks-asg-rolling-update-handler#129]
### Describe the bug

We're running `Cluster Autoscaler` and `aws-eks-asg-rolling-update-handler` in the same EKS cluster. While `Cluster Autoscaler` was trying to scale up the nodes due to increased traffic, `aws-eks-asg-rolling-update-handler` made a `SetDesiredCapacityInfo` request that lowered the number of active instances in ASG, causing an outage.

```
    "eventTime": "2023-06-28T23:21:46Z",
    "arn": "arn:aws:iam::xxxxx:role/xxxxx-aws-eks-asg-rolling-update-handler",
    "requestParameters": {
        "desiredCapacity": 90,
        "autoScalingGroupName": "xxxxx-2022020200515369970000000b",
        "honorCooldown": true
    },
    "requestID": "b02fcaa3-cbbd-4d13-a183-828fdae4477f",
    "eventID": "41e31359-c299-4481-bed5-06bed8261347",
```

ASG activity history
```
Successful
Terminating EC2 instance: i-0f525e751d21ff18b	
At 2023-06-28T23:21:46Z a user request explicitly set group desired capacity changing the desired capacity from 99 to 90. 
At 2023-06-28T23:21:48Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 99 to 90. 
At 2023-06-28T23:21:49Z instance i-087d61bdf2a96135d was selected for termination. 
At 2023-06-28T23:21:49Z instance i-07c86111988c8f033 was selected for termination. 
At 2023-06-28T23:21:49Z instance i-0635b60dc9625ee25 was selected for termination.
At 2023-06-28T23:21:49Z instance i-036cf4d15fee9fe41 was selected for termination.
At 2023-06-28T23:21:49Z instance i-021dc05fa50e14344 was selected for termination.
At 2023-06-28T23:21:49Z instance i-012bfb97195f1054d was selected for termination.
At 2023-06-28T23:21:49Z instance i-0fcd7d7595f9e49a8 was selected for termination.
At 2023-06-28T23:21:50Z instance i-0f9a8745a9e9f2e23 was selected for termination.
```

* There should be a portion in the docs about enabling [ASG Scale In Protection](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html) on all the ASG & Active Nodes for safety
* There should be an option in `aws-eks-asg-rolling-update-handler` to not use `SetDesiredCapacityInfo` by itself and instead rely on `Cluster Autoscaler` to bring up new nodes. `aws-eks-asg-rolling-update-handler` should evict node and let `Cluster Autoscaler` deal with missing nodes

### List the steps that must be taken to reproduce this issue

Create EKS cluster environment with `Cluster Autoscaler` & `aws-eks-asg-rolling-update-handler` enabled

While rolling through nodes with many pods with PDB of `maxUnavailable: 0`, keep on increasing hpa to cause `Cluster Autoscaler` to bring up new nodes. 

At some point, because of 5 minute timeout of eviction, `aws-eks-asg-rolling-update-handler` will be out of sync with the number of nodes of what `Cluster Autoscaler` brought up and `aws-eks-asg-rolling-update-handler` will send `SetDesiredCapacityInfo` that is lower than the current ASG size

### Version

1.8.0

**Comment by TwiN** [comment]
Great catch. This has never happened to me, but I can see how it could happen with enough bad luck.

**Comment by TwiN** [comment]
@russki would you mind testing the new `latest` Docker image? No need to attempt to replicate the issue exactly - I just don't have the bandwidth to test the changes in a real cluster at the moment.
