### ISSUE TITLE
GracePeriod in client.Drain() should be configurable

### ISSUE THREAD

**Issue by LaCodon** [TwiN/aws-eks-asg-rolling-update-handler#28]
### Describe the feature request

In `client.Drain()` the value of `GracePeriodSeconds` is hard coded but should be configurable via an environment variable. The default should stay `-1` if no other value is set.

### Why do you personally want this feature to be implemented?

Letting the Pod decide how long the GracePeriod should be is perfectly fine for production environments in order to not forcefully delete any workload but for test environments this delays the rolling update a lot.

I have a lot of pods with different GracePeriod configurations on a large amount of nodes and thus I would like to increase the rolling update speed by setting a smaller GracePeriod. Setting a small GracePeriod introduces the risk of forcefully killing Pods before they terminated gracefully but one might be totally fine with such behaviour in explained circumstances.

### Additional information

I would be happy to implement this feature myself during the next weeks if @TwiN is fine with the proposal

**Comment by TwiN** [comment]
Released in [v1.5.0](https://github.com/TwiN/aws-eks-asg-rolling-update-handler/releases/tag/v1.5.0)
